### ISSUE TITLE
Work division

### ISSUE THREAD

**Issue by dreday966** [cscm94go/CSCM94Go#3]
I think we should discuss how to divide work to every members firstly.

**Comment by zakariyeali** [comment]
This project should be divided roughly in to the following sections. Please note there will be overlap on some of the models in these sections. For these particular models, one person should take responsibility.

**4 Sections:**

1. Game (Models, views Controller) @dreday966 
2. Account (Models, views, Controller) @zakariyeali 
3. Admin(models, views, controller) @hectorvalsan 
4. Home(models, views, controller) @idrisomar1 

**Extra Section:**
5. DatabaseClass ("context class" that will contain most db operations needed) @zakariyeali 


**Owner of Database related issues @zakariyeali  
Owner of Game related issues @dreday966**

**Comment by zakariyeali** [comment]
All tasks divided between team.
