### ISSUE TITLE
Storyboard

### ISSUE THREAD

**Issue by dreday966** [cscm94go/CSCM94Go#6]
### 1.First login page, login page can switch to sign up page.
after login go to user dashboard
### 2.Signup page, Signup page can switch to sign up page.
after signup go to user dashboard

### todo other pages to do

**Comment by zakariyeali** [comment]
@dreday966  yes, this issue is one I am already dealing with see #5

**Comment by zakariyeali** [comment]
This has been completed... 
`        else if (login(user) == true) {
            HelperMethods.LoadScene("/fxml/HomeDashboard.fxml");
            HelperMethods.showAlert(Alert.AlertType.CONFIRMATION, Main.stage, "Enter!",
                    "Welcome " + usernameField.getText());
        }
`

`registerUser(firstName, lastName, username);
        HelperMethods.LoadScene("/fxml/application.fxml");
        if(firstName.isEmpty() || lastName.isEmpty() || username.isEmpty()) {
            HelperMethods.showAlert(Alert.AlertType.ERROR, Main.stage, "Form Error!", "Please ensure all fields are right!");
            return;
        }
        else if (registerUser(firstName, lastName, username) == true) {
            HelperMethods.showAlert(Alert.AlertType.CONFIRMATION, Main.stage, "Registration Success!",
                    "New user " + user_name.getText() + " has been created.");
        }`
